language: python
python:
    - "2.7"
install:
    - python setup.py install
    - pip install coverage
    - pip install pep8
script:
    - find ./pyactor -name \*.py -exec pep8 --ignore=E402 {} + 
    - coverage run testing/tests.py
after_success:
    - pip install coveralls
    - coveralls
    - bash <(curl -s https://codecov.io/bash)
