language: python
python:
    - "2.7"
install:
    - python setup.py install
    - pip install coverage
script: coverage run testing/tests.py
after_success:
    - pip install coveralls
    - coveralls
    - bash <(curl -s https://codecov.io/bash)
    
