language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - nosetests -v --with-coverage --cover-erase --cover-package=pyactor
after_success:
    - pip install coveralls
    - coveralls
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
